name: Flask App Pipeline

on:
  push:
    branches:
      - main

jobs:
  python-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setting python in runner
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Installing dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running the flask application
        run: |
          python app.py &
          sleep 10

      - name: Ecoing something
        run: echo "Hurray! Running..."

      - name: Testing CURL
        run: curl http://127.0.0.1:5000
