name: Flask App Pipeline

on:
  push:
    branches:
      - main

jobs:
  python-app:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4

      - name: Setting python in runner
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Installing dependecies
        run: |
          python -m pip install --upgrade pip
          pip install -r requitements.txt

      - name: Ecoing something
        run: echo "Hurray! Running..."
